# Generated by Django 5.2 on 2025-05-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinesDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('composition', models.TextField()),
                ('uses', models.TextField()),
                ('side_effects', models.TextField()),
                ('image_url', models.URLField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('excellent_review', models.FloatField()),
                ('average_review', models.FloatField()),
                ('poor_review', models.FloatField()),
                ('text', models.TextField()),
                ('embedding', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Medicines Detail',
                'verbose_name_plural': 'Medicines Details',
                'db_table': 'medicines_detail',
            },
        ),
    ]
